### Homework 1 Practice

In [1]:
def silly_func():
    '''
    This is just a practice function
    '''
    return 2, 1, "hey there"  #always return what you want the answer to be
a,b,c=silly_func()
print(a,b,c)

2 1 hey there


In [2]:
def count_capitals(inString): #step 2: this is the defining of a function
    numCaps=0                  

    for char in inString:
        if char.isupper():
            numCaps +=1
        
    return numCaps   #step 1. what do you want the return to be? Return numCaps

print(count_capitals('Go Tigers!')) # leave this, it's a test unit
print(count_capitals('Hail to the Victors Valiant!')) # leave this, it's a test unit
print(count_capitals("LET'S GO DEVILS!")) # leave this, it's a test unit

2
3
12


# Intro to Numpy

In [3]:
import numpy as np # by convention, numpy is always imported with the alias np
import random

### An example that shows why Python is slow is the following:

In [4]:
# a "+" sign isn't just a plus sign
a,b=3, 14
print(a+b)
a,b="py ","is good"
print(a+b)

17
py is good


### So here is an example: Let's pull random numbers and square them:

In [5]:
%%time

y = 0     
for i in range(1000000):
    x = random.uniform(0, 1)
    y += x**2

CPU times: user 441 ms, sys: 9.38 ms, total: 451 ms
Wall time: 413 ms


### The speed solution 
**Vectorization**. Send commands on arrays to the computer pre-compiled, with efficient native machine code.

Let's redo the code above:

In [6]:
%%time

x = np.random.uniform(0, 1, 1000000)
y = np.sum(x**2)

CPU times: user 18.6 ms, sys: 8.51 ms, total: 27.1 ms
Wall time: 25.8 ms


### Common methods:

1. np.array([user defined list, or lists of lists]) creates an array or matrix
2. np.ones(how many) and np.ones([rows,cols]), same but all elements are 1
3. np.zeros(how many) and np.zeros([rows,cols]), same but all elements are 0
4. np.arange(start,end,stepsize) , creates array, note that the array will not include any elements >=end
5. np.linspace(from,to,# of elements), creates array covering the range specified
6. np.eye(#) creates an identity matrix of size #x#
7. np.concatenate([x, y]) combines arrays x and y
8. np.nan is a NaN object (e.g. like a missing element in a data table)
9. np.ceil(#), np.floor(#) if #=3.4, ceil will return 4, and floor will return 3.
10. np.max(x), np.min(x), np.average(x), np.mediam(x) and many more statistical operations work as you would expect
11. np.reshape(x,[rows,cols]) works as it looks
12. np.random.<dist> can draw random numbers from many distributions

### ASIDE: ALWAYS SET A SEED! 
Why have I emphasized a "seed" so much? Well, suppose you run analysis, and in it, you draw random numbers.

In [7]:
vector = np.random.uniform(0,1,10)
print(vector)

[0.20034353 0.21359254 0.16763608 0.56544677 0.71566734 0.28068908
 0.21907147 0.82679012 0.49017546 0.91681038]


### HOW TO SET A SEED:

In [8]:
np.random.seed(100) # the seed is 100
vector = np.random.uniform(0,1,10)
np.random.seed(100)
vector2 = np.random.uniform(0,1,10)
print(vector==vector2)

[ True  True  True  True  True  True  True  True  True  True]


# The dark side of vectors and numpy 
1. You can't vectorize every operation :(
2. Can be prohibitive, memory-wise: When you run an array operation, Python creates the entire array and puts it into memory, then runs it. A vector of length 1,000,000,000,000 is huge and requires substantial memory to create. By contrast, you can execute for i in range(1,000,000,000,000): pass without causing an issue, because Python **never created that vector, it just iterated over numbers**. This is because range(#) is a "generator" and not an explicit object.


# Numpy Practice: (After Class HW)

In [9]:
a = np.arange(4).reshape((2,2))
print("array a:")
print(a)

print("\nMaximum value of a:")
print(np.amax(a)) # put your answer inside the print

print("\nMinimum value of a:")
print(np.amin(a)) # put your answer inside the print

print("\nReturn an array of the max in each column of a:")
print(np.amax(a[:,0])) # put your answer inside the print
print(np.amax(a[:,1]))

print("\nReturn an array of the min in each row of a:")
print(np.amax(a[0])) # put your answer inside the print
print(np.amax(a[1]))

print("\nReturn a, sorted within each row:")
print(np.sort(a,axis=0))

print("\nReturn a, sorted within each column:")
print(np.sort(a,axis=1))

array a:
[[0 1]
 [2 3]]

Maximum value of a:
3

Minimum value of a:
0

Return an array of the max in each column of a:
2
3

Return an array of the min in each row of a:
1
3

Return a, sorted within each row:
[[0 1]
 [2 3]]

Return a, sorted within each column:
[[0 1]
 [2 3]]


In [10]:
b = np.arange(40).reshape((20,2))
print("array b:")
print(b)

print("\nPrint elements of the first column of b above that column's 80th percentile:")
print(np.percentile(b, 50, axis=0)) 

print("\nCovariance matrix of the columns of b:")
print(np.cov(b))


array b:
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]
 [24 25]
 [26 27]
 [28 29]
 [30 31]
 [32 33]
 [34 35]
 [36 37]
 [38 39]]

Print elements of the first column of b above that column's 80th percentile:
[19. 20.]

Covariance matrix of the columns of b:
[[0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5
  0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5
  0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5
  0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5
  0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5
  0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5
  0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5
  0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5
  0.5 0.5]
 [